### PR TITLE
Fixed some minor typos and inconsistencies in variable naming

### LINKED ISSUE #1542: Fix some typos and namings

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #1542 and maybe makes #1396 easier to review

this PR 
- changes cosphiRated to cosPhiRated and aligns this overall classes
- changes olmcharacteristics to olmCharacteristics
- fixes some more minor typos

### CODE REVIEW

File: src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java [hunk 1]
```diff
@@ -13,19 +13,19 @@
 import javax.measure.quantity.Power;
 import tech.units.indriya.ComparableQuantity;
 
-/** Describes the type of a {@link edu.ie3.datamodel.models.input.system.HpInput} */
+/** Describes the type of {@link edu.ie3.datamodel.models.input.system.HpInput} */
 public class HpTypeInput extends SystemParticipantTypeInput {
-  /** Thermal output of the heat pump (typically in kW), when sRated * cosphi_rated is consumed */
+  /** Thermal output of the heat pump (typically in kW), when sRated * cosPhi_rated is consumed */
```
Comment (sebastian-peter) [inline src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java]:
```suggestion
  /** Thermal output of the heat pump (typically in kW), when sRated * cosPhiRated is consumed */
```

File: src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java [hunk 2]
```diff
@@ -13,19 +13,19 @@
...
    * @param uuid of the input entity
    * @param id of this type of HP
-   * @param capex Captial expense for this type of HP (typically in €)
+   * @param capex Capital expense for this type of HP (typically in €)
    * @param opex Operating expense for this type of HP (typically in €)
-   * @param cosphiRated Power factor for this type of HP
+   * @param cosPhiRated Power factor for this type of HP
    * @param sRated Rated apparent power
-   * @param pThermal Thermal output of the heat pump, when sRated * cosphi_rated is consumed
+   * @param pThermal Thermal output of the heat pump, when sRated * cosPhi_rated is consumed
```
Comment (sebastian-peter) [inline src/main/java/edu/ie3/datamodel/models/input/system/type/HpTypeInput.java]:
```suggestion
   * @param pThermal Thermal output of the heat pump, when sRated * cosPhiRated is consumed
```

File: src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactoryTest.groovy
Comment (sebastian-peter) [inline src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactoryTest.groovy:1]: Everything's supposed to be lower case here, I think. Same for all other tests

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Thanks for cleaning up. Some comments from my side.

File: src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactoryTest.groovy
Comment (danielfeismann) [reply src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactoryTest.groovy:1]: I think you are right. Looks like this drifted a bit appart in the other test over the time, I think. Maybe this should be checked in general. However should not be handled in this PR.

Comment (danielfeismann) [reply src/test/groovy/edu/ie3/datamodel/io/factory/input/participant/EvcsInputFactoryTest.groovy:1]: Moved to #1544

**Review by sebastian-peter — APPROVED** [review]
