### PR TITLE
Fix equals method of EnergyPriceValue

### LINKED ISSUE #1479: Fix `EnergyPriceValue.equals()` method

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #1479

### CODE REVIEW

File: src/main/java/edu/ie3/datamodel/models/value/EnergyPriceValue.java [hunk 1]
```diff
@@ -32,12 +32,14 @@ public boolean equals(Object o) {
     if (this == o) return true;
     if (o == null || getClass() != o.getClass()) return false;
     EnergyPriceValue that = (EnergyPriceValue) o;
-    return Objects.equals(price, that.price);
+
+    return price.getValue().doubleValue() == that.price.getValue().doubleValue()
+        && price.getUnit().equals(that.price.getUnit());
```
Comment (staudtMarius) [inline src/main/java/edu/ie3/datamodel/models/value/EnergyPriceValue.java]: Does it makes sense to use `Objects.equals(price.getUnit(), that.price.getUnit())` instead?

File: src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/TimeBasedSimpleValueFactoryTest.groovy [hunk 2]
```diff
@@ -110,7 +110,7 @@ class TimeBasedSimpleValueFactoryTest extends Specification {
         )
 
     expect:
-    factory.buildModel(data) == expected
+    factory.buildModel(data).equals(expected)
```
Comment (staudtMarius) [inline src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/TimeBasedSimpleValueFactoryTest.groovy]: I think it would be better to use `Objects.equals()` for the tests, since the intellij won't suggest switching to `==`.

**Review by staudtMarius — CHANGES_REQUESTED** [review]
Looks good to me, Just two small comments.

**Review by staudtMarius — APPROVED** [review]
LGTM.
