### PR TITLE
Fix Irradiation / Irradiance

### LINKED ISSUE #266: Fix Irradiance/Irradiation
Currently the old, invalid version of irradiance and irradiation is used within the PSDM. 
This affects the `StandardUnits` as well as several other places. 

The following changes are needed:

- adapt `StandardUnits` to use irradiance and irradiation correctly
- adapt `StandardUnits` to use `WATT_PER_SQUAREMETER` as standard irradiance and `WATTHOUR_PER_SQUAREMETER` as standard irradiation

### PR DESCRIPTION
**Pull request by johanneshiry**
Resolves #266

### CODE REVIEW

File: src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/IconTimeBasedWeatherValueFactoryTest.groovy [hunk 1]
```diff
@@ -115,15 +115,15 @@ class IconTimeBasedWeatherValueFactoryTest extends Specification {
 		actual.with {
 			assert it.time == TimeUtil.withDefaults.toZonedDateTime("2019-08-01 01:00:00")
 			assert it.value.coordinate == coordinate
-			assert it.value.irradiation.directIrradiation.isPresent()
-			assert it.value.irradiation.directIrradiation.get() == Quantities.getQuantity(0.002317613203124999, PowerSystemUnits.KILOWATT_PER_SQUAREMETRE)
-			assert it.value.irradiation.diffuseIrradiation.isPresent()
-			assert it.value.irradiation.diffuseIrradiation.get() == Quantities.getQuantity(0.0018088226191406245, PowerSystemUnits.KILOWATT_PER_SQUAREMETRE)
-			assert it.value.temperature.temperature.isPresent()
+			assert it.value.solarIrradiance.directIrradiance.present
+			assert it.value.solarIrradiance.directIrradiance.get() == Quantities.getQuantity(0.002317613203124999, PowerSystemUnits.KILOWATT_PER_SQUAREMETRE)
```
Comment (ckittl) [inline src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/IconTimeBasedWeatherValueFactoryTest.groovy:119]: I would have expected this... :thinking: 
```suggestion
			assert it.value.solarIrradiance.directIrradiance.get() == Quantities.getQuantity(2.317613203124999, PowerSystemUnits.WATT_PER_SQUAREMETRE)
```

File: src/main/java/edu/ie3/datamodel/io/factory/timeseries/PsdmTimeBasedWeatherValueFactory.java [hunk 2]
```diff
@@ -70,10 +75,10 @@ public String getTimeFieldString() {
...
     java.util.UUID uuid = data.getUUID(UUID);
     ZonedDateTime time = timeUtil.toZonedDateTime(data.getField(TIME));
-    ComparableQuantity<Irradiation> directIrradiation =
-        data.getQuantity(DIRECT_IRRADIATION, StandardUnits.IRRADIATION);
-    ComparableQuantity<Irradiation> diffuseIrradiation =
-        data.getQuantity(DIFFUSE_IRRADIATION, StandardUnits.IRRADIATION);
+    ComparableQuantity<Irradiance> directIrradiance =
+        data.getQuantity(DIRECT_IRRADIANCE, StandardUnits.SOLAR_IRRADIANCE);
+    ComparableQuantity<Irradiance> diffuseIrradiance =
+        data.getQuantity(DIFFUSE_IRRADIANCE, StandardUnits.SOLAR_IRRADIANCE);
```
Comment (ckittl) [inline src/main/java/edu/ie3/datamodel/io/factory/timeseries/PsdmTimeBasedWeatherValueFactory.java:81]:
```suggestion
    ComparableQuantity<Irradiance> directIrradiance =
        data.getQuantity(DIRECT_IRRADIANCE, PowerSystemUnits.WATT_PER_SQUAREMETRE);
    ComparableQuantity<Irradiance> diffuseIrradiance =
        data.getQuantity(DIFFUSE_IRRADIANCE, PowerSystemUnits.WATT_PER_SQUAREMETRE);
```

Would make it explicitly here as well.

**Review by ckittl — CHANGES_REQUESTED** [review]

File: src/main/java/edu/ie3/datamodel/models/value/IrradiationValue.java [hunk 3]
```diff
@@ -13,22 +13,22 @@
 
 /** Describes an irradiation value as a pair of diffuse and direct radiation */
 public class IrradiationValue implements Value {
```
[the remark this answers is not in the document]
Comment (johanneshiry) [reply src/main/java/edu/ie3/datamodel/models/value/IrradiationValue.java:15]: Resolved by deleting `IrradiationValue` as it is actually not required anymore

File: src/main/java/edu/ie3/datamodel/io/factory/timeseries/PsdmTimeBasedWeatherValueFactory.java [hunk 4]
```diff
@@ -28,6 +28,11 @@
  */
 public class PsdmTimeBasedWeatherValueFactory extends TimeBasedWeatherValueFactory {
   private static final String COORDINATE = "coordinate";
+  private static final String DIFFUSE_IRRADIANCE = "diffuseirradiation";
+  private static final String DIRECT_IRRADIANCE = "directirradiation";
```
[the remark this answers is not in the document]
Comment (johanneshiry) [reply src/main/java/edu/ie3/datamodel/io/factory/timeseries/PsdmTimeBasedWeatherValueFactory.java:32]: See #267

File: src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/IconTimeBasedWeatherValueFactoryTest.groovy (hunk 1 above)
Comment (johanneshiry) [reply src/test/groovy/edu/ie3/datamodel/io/factory/timeseries/IconTimeBasedWeatherValueFactoryTest.groovy:119]: groovy `==` first checks `compareTo` and uses `a.comporeTo(b) == 0` if a `compareTo` method exists. Otherwise it will use `equals`. As  a `compareTo` method exists for the quantity implementation, it is called first. This `compareTo` converts units if necessary and `0.002317613203124999 kW/m^2 = 2.317613203124999 W/m^2`. Hence the assert is `true`.

**Review by ckittl — APPROVED** [review]
