### PR TITLE
Fixed valid fields for `EmInput`

### LINKED ISSUE #1360: Fix valid fields for em inputs

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #1360

### CODE REVIEW

File: src/test/groovy/edu/ie3/datamodel/io/factory/input/EmInputFactoryTest.groovy [hunk 1]
```diff
@@ -24,6 +24,79 @@ class EmInputFactoryTest extends Specification {
...
+      [
+        "uuid",
+        "id",
+        "controlStrategy",
+        "controllingEm",
+        "operator",
+        "operatesFrom",
+        "operatesUntil"
+      ] as Set,
+    ]
```
Comment (danielfeismann) [inline src/test/groovy/edu/ie3/datamodel/io/factory/input/EmInputFactoryTest.groovy:91]: You see any change to reduce this by some method creating the combinations?

**Review by danielfeismann — CHANGES_REQUESTED** [review]
Thanks for take car of this! Looks good except for one thing
