### PR TITLE
Fixing `CsvSystemParticipantSourceTest`

### LINKED ISSUE #958: Fix `CsvSystemParticipantSourceTest`
`CsvSystemParticipantSourceTest` is broken because the tests do not fail for neither `Try.Success` or `Try.Failure`. So, if all parsing fails for whatever reason, the tests do not fail.
What could solve this is another parameter for each test `shouldSucceed`, so that we can match against expected successes and failures.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #958

### CODE REVIEW

File: src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy [hunk 1]
```diff
@@ -92,23 +92,39 @@ class CsvSystemParticipantSourceTest extends Specification implements CsvTestDat
...
+    def nodeMap = map([sptd.hpInput.node])
+
+    expect:
+    def heatPumps = Try.of(() -> csvSystemParticipantSource.getHeatPumps(map(operators), nodeMap, map(types), map(thermalBuses)), SourceException)
+
+    heatPumps.failure
+    heatPumps.exception.get().class == SourceException
+
+    where:
+    nodes               | operators               | types               | thermalBuses              | resultingSize || resultingSet
```
Comment (sebastian-peter) [inline src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy:120]: I think it's my mistake, but the `nodes` attribute is not used here. Should be `map(nodes)` in line 111, which you can just integrate into line 120. 

Please also check the tests below

File: src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy [hunk 2]
```diff
@@ -92,23 +92,39 @@ class CsvSystemParticipantSourceTest extends Specification implements CsvTestDat
...
       new HpInput(sptd.hpInput.uuid, sptd.hpInput.id, OperatorInput.NO_OPERATOR_ASSIGNED, sptd.hpInput.operationTime, sptd.hpInput.node, sptd.hpInput.thermalBus, sptd.hpInput.qCharacteristics, sptd.hpInput.type)
     ]
-    []                  | []                      | []                  | []                        || 0             | []
-    [sptd.hpInput.node] | []                      | []                  | []                        || 0             | []
-    [sptd.hpInput.node] | [sptd.hpInput.operator] | []                  | []                        || 0             | []
-    [sptd.hpInput.node] | [sptd.hpInput.operator] | [sptd.hpInput.type] | []                        || 0             | []
+    [] | [] | [] | []                                                        || 0             | []
+    [sptd.hpInput.node] | []                      | []                  | [] || 0             | []
+    [sptd.hpInput.node] | [sptd.hpInput.operator] | []                  | [] || 0             | []
+    [sptd.hpInput.node] | [sptd.hpInput.operator] | [sptd.hpInput.type] | [] || 0             | []
```
Comment (sebastian-peter) [inline src/test/groovy/edu/ie3/datamodel/io/source/csv/CsvSystemParticipantSourceTest.groovy:127]: Just a minor point, but the columns are now misaligned here. Please also check below

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Besides some superficial nodes from my side, this looks good. Thanks!

**Review by sebastian-peter — APPROVED** [review]
Thanks, looks great!
