### PR TITLE
address #264 correctly

### LINKED ISSUE #264: NullPointerException when no operator headline in .csv file is present
The current CsvDataSource implementation lacks the check for a missing "operator" field in the .csv-input data which causes a NPE in `CsvDataSource:241`. 

This could be avoided by using the already existing fallback in `CsvDataSource:241`. It just needs to be extended by a null check.

### PR DESCRIPTION
**Pull request by johanneshiry**
Finally resolves #264

### CODE REVIEW

File: src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java [hunk 1]
```diff
@@ -266,7 +275,7 @@ private OperatorInput getFirstOrDefaultOperator(
    *
    * }</pre>
    *
-   * ...
+   * <p>...
```
Comment (ckittl) [inline src/main/java/edu/ie3/datamodel/io/source/csv/CsvDataSource.java:278]: This is no proper syntax. Even the XHTML-shorthand `<p/>` would be discouraged.

```suggestion
   * <p>...</p>
```

**Review by ckittl — APPROVED** [review]
Sorry, for letting the last PR regarding #264 pass. I simply got your issue wrong... :disappointed: 

Despite of possibly accepting my pedantic, feel free to close and merge.

**Review by ckittl — DISMISSED** [review]

**Review by ckittl — APPROVED** [review]
